name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install iOS Simulator Runtime
        run: xcodebuild -downloadPlatform iOS

      - name: Test
        run: |
          xcodebuild test \
            -project Quoti/Quoti.xcodeproj \
            -scheme Quoti \
            -destination 'platform=iOS Simulator,name=Any iOS Simulator Device' \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}
